### ISSUE TITLE
Fails to create functioning venv on ubuntu 18

### ISSUE THREAD

**Issue by mhammond** [badboy/xshell-venv#3]
On ubuntu a simple `python3 -m venv test-env` fails with:

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/skip/test-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```
(although the venv directory *is* created, it just fails to work in any sane way as it does not have `pip`)

However, python3-venv is installed:
```
skip@eden:~$ sudo apt-get install python3-venv
[sudo] password for skip:
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-venv is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 273 not upgraded.
```

and sure enough:
```
skip@eden:~$ python3 -m ensurepip
/usr/bin/python3: No module named ensurepip
```

According to https://askubuntu.com/questions/879437/ensurepip-is-disabled-in-debian-ubuntu-for-the-system-python, this is "expected" :( The work-around of:

`python3 -m venv target/debug/venv-py3-glean_parser --without-pip --system-site-packages` does work, and is enough to get glean_build working. However, `glean_parser` ends up installed in system site packages, which isn't ideal - but without this work-around it was still being installed into site-packages (because the venv doesn't have a pip) but at least it works now.

(IOW, that work-around doesn't seem like the right thing in most cases, but was enough to get me past the immediate problem.)

**Comment by badboy** [comment]
What ubuntu is that?
In a local Ubuntu 22.04 in Docker it works for me after installing `python3.10-venv`:

```
root@294cde8ab8e2:~# apt install python3
[...]
root@294cde8ab8e2:~# python3 -m venv test-env
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/root/test-env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

root@294cde8ab8e2:~# apt install python3.10-venv
[...]
root@294cde8ab8e2:~# python3 -m venv test-env
root@294cde8ab8e2:~# . test-env/bin/activate
(test-env) root@294cde8ab8e2:~# python3 -m ensurepip
Looking in links: /tmp/tmptxynbu_0
Requirement already satisfied: setuptools in ./test-env/lib/python3.10/site-packages (59.6.0)
Requirement already satisfied: pip in ./test-env/lib/python3.10/site-packages (22.0.2)
(test-env) root@294cde8ab8e2:~# python3 -m pip

Usage:
  /root/test-env/bin/python3 -m pip <command> [options]
[...]
```

There's not much this library can do if the system is misbehaving or missing packages.
We can and should of course document more properly that these packages are needed.

**Comment by mhammond** [comment]
> What ubuntu is that?

18.04 LTS, which has Python 3.8.

> There's not much this library can do if the system is misbehaving or missing packages.
> We can and should of course document more properly that these packages are needed.

From the links above, it's not clear that it's misbehaving and that it's working as intended (as misguided as that is). IOW, there's no reasonable way I can find to install the necessary packages on that Ubuntu.

An option would be to just check pip exists but ensurepip doesn't, then just use the system site packages option. I understand this isn't a priority though.

**Comment by badboy** [comment]
Default `python3` package on Ubuntu seems to be 3.6.
`python3-venv` is made for that and that combination seems to work just fine.

It also has `python3.8` and `python3.8-venv` and that combination seems to also work.
That doesn't bring a `python3` binary, but that can be fixed with `update-alternatives --install /usr/bin/python3 python3 $(which python3.8) 20`

I'm not really keen on having to handle all the weird ways Python gets deployed these days, especially on old Ubuntu.

**Comment by mhammond** [comment]
> I'm not really keen

I wish this was an abstract issue for me, but ok

**Comment by badboy** [comment]
> > I'm not really keen
> 
> I wish this was an abstract issue for me, but ok

Heh, sorry. I get it and given that this is used within Glean we might need to fix it to be used in our environments.

Where do you run into this? 
As shown above in my test environment (Docker containers) using the right versions of tools seems to solve it.
So I'd rather recommend that then making this tool try to work around Ubuntu's packaging awkardness.

**Comment by mhammond** [comment]
This is on WSL :(

> It also has `python3.8` and `python3.8-venv` and that combination seems to also work.
> That doesn't bring a `python3` binary, but that can be fixed with `update-alternatives --install /usr/bin/python3 python3 $(which python3.8) 20`

That's how I ended up with 3.8 in the first place. However, you seem to have put me on the right track. Trying to install via `virtualenv` didn't work, and while I thought I had tried python38-venv, trying it again seems to have worked - I've gone from a simple "no module" error to:

```
skip@eden:/mnt/c/src/moz/application-services$ python3 -m ensurepip
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules for the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.
```

Which isn't obvious, but `ensurepip` now works in a virtualenv (just not in the system python) - so I'm unblocked here. I'll close this and leave it up to you if you think doc or any other changes are worthwhile.

Thanks!
