### ISSUE TITLE
Wanna maintain xshell? 

### ISSUE THREAD

**Issue by matklad** [badboy/xshell-venv#6]
Hey, I think that `xshell` is a rather valuable thing to have in the Rust ecosystem, but its current state is _very_ far from what it should be. I am not really maintaining it all that well, and I am about to switch to https://github.com/dsherret/dax for my main use of xshell (personal scripts over here https://github.com/matklad/config/blob/master/xtool/src/main.rs), so the maintainance might lapse even further behind. I am wondering if you might be interested in taking over? :D

**Comment by matklad** [comment]
and yeah, by maintain I really mean "take the design in whatever direction would be best" --- in terms of just keeping the lights on, I hope I am doing acceptable job, but I really feel that more should be done in terms of features and such

**Comment by badboy** [comment]
Hey, thanks for reaching out!
Right now I don't think I have the time or energy to take over xshell and take it in any direction; I just don't use it enough.
If it comes down to "keep the lights on whatever there is" though I would be willing to do that.
Though if you have anyone else that wants to invest more time that would be even better.

**Comment by matklad** [comment]
Seems like you perfectly understand the situation I am in :D
